### ISSUE TITLE
Investment Tracking

### ISSUE THREAD

**Issue by DoshiHarsh** [DoshiHarsh/Personal-Finance-Tracker#6]
Add support to track investments from different accounts, add individual asset tracking and manual updating of current value. 

- [ ] Investment account creation UI and backend tables
- [ ] Investment transaction tracking (ETF, individual stocks, Mutual funds, Options)
- [ ] RSU/Stock options transactions
- [ ] Update current value of investment assets (as of date)
- [ ] Net worth progress
